import sys
from agent.fitness_agent import FitnessAgent


ACTIVITY_OPTIONS = {
    "1": ("sedentary",   "Little or no exercise (desk job)"),
    "2": ("light",       "Light exercise 1–3 days/week"),
    "3": ("moderate",    "Moderate exercise 3–5 days/week"),
    "4": ("active",      "Hard exercise 6–7 days/week"),
    "5": ("very_active", "Physical job or twice-daily training"),
}

GOAL_OPTIONS = {
    "1": ("weight_loss",  "Lose body fat"),
    "2": ("muscle_gain",  "Build muscle mass"),
    "3": ("maintenance",  "Maintain current weight and fitness"),
}

EXPERIENCE_OPTIONS = {
    "1": ("beginner",      "Less than 1 year of consistent training"),
    "2": ("intermediate",  "1–3 years of consistent training"),
    "3": ("advanced",      "3+ years of consistent training"),
}


def _prompt_number(label: str, cast):
    while True:
        raw = input(label).strip()
        try:
            return cast(raw)
        except ValueError:
            print("  Please enter a valid number.")


def _prompt_choice(label: str, options: dict) -> str:
    for key, (value, description) in options.items():
        print(f"  {key}. {value.replace('_', ' ').title()} — {description}")
    while True:
        choice = input(label).strip()
        if choice in options:
            return options[choice][0]
        print(f"  Please enter one of: {', '.join(options.keys())}")


def _print_separator(width: int = 62) -> None:
    print("=" * width)


def _print_plan(plan: dict) -> None:
    _print_separator()
    print(f"  AI FITNESS PLAN FOR: {plan['name'].upper()}")
    print(f"  Goal: {plan['goal'].replace('_', ' ').title()}")
    _print_separator()

    cal = plan["nutrition"]["calories"]
    mac = plan["nutrition"]["macros"]

    print("\n--- NUTRITION ---")
    print(f"  Basal Metabolic Rate (BMR) : {cal['bmr']} kcal")
    print(f"  Total Daily Energy (TDEE)  : {cal['tdee']} kcal")
    print(f"  Daily Calorie Target       : {cal['target_calories']} kcal"
          f"  (goal adjustment: {cal['adjustment_kcal']:+d} kcal)")
    print(f"\n  Macronutrient Targets:")
    print(f"    Protein : {mac['protein_g']:>4} g  ({mac['protein_pct']}%)")
    print(f"    Carbs   : {mac['carbs_g']:>4} g  ({mac['carbs_pct']}%)")
    print(f"    Fat     : {mac['fat_g']:>4} g  ({mac['fat_pct']}%)")

    wkt = plan["workout"]
    print(f"\n--- WEEKLY WORKOUT PLAN ---")
    print(f"  Focus      : {wkt['focus']}")
    print(f"  Training days/week : {wkt['days_per_week']}")

    for day, details in wkt["schedule"].items():
        duration = f"({details['duration_min']} min)" if details["duration_min"] > 0 else ""
        print(f"\n  {day}: {details['type']} {duration}")

        if details["exercises"]:
            print(f"    {'Exercise':<32} {'Sets':>4} {'Reps':>9} {'Rest':>7}")
            print("    " + "-" * 55)
            for ex in details["exercises"]:
                print(f"    {ex['name']:<32} {str(ex['sets']):>4} {ex['reps']:>9} {ex['rest']:>7}")

        if details.get("notes"):
            print(f"    → {details['notes']}")

    _print_meal_plan(plan.get("meal_plan", {}))

    print()
    _print_separator()
    print("  Plan generated by AI Fitness Planner Agent")
    _print_separator()
    print()


def _print_meal_plan(meal_plan: dict) -> None:
    if not meal_plan:
        return

    print(f"\n--- 7-DAY MEAL PLAN  (AI generated · {meal_plan.get('model_used', 'llama3.2')}) ---")
    print(f"  Daily target: {meal_plan.get('target_calories')} kcal")

    if "error" in meal_plan:
        print(f"\n  [!] {meal_plan['error']}")
        return

    days = meal_plan.get("days", {})
    if not days:
        print("\n  (raw output below)")
        print(meal_plan.get("raw", ""))
        return

    for day, meals in days.items():
        print(f"\n  {day}:")
        for meal_key in ("breakfast", "lunch", "dinner", "snack", "daily_total"):
            if meal_key in meals:
                label = meal_key.replace("_", " ").title()
                print(f"    {label}: {meals[meal_key].split(':', 1)[-1].strip()}")


def main() -> None:
    print("\n" + "=" * 62)
    print("         AI Fitness Planner Agent")
    print("=" * 62)
    print("Answer a few questions to receive your personalised plan.\n")

    name   = input("Your name: ").strip() or "User"
    age    = _prompt_number("Age (years): ", int)
    weight = _prompt_number("Weight (kg): ", float)
    height = _prompt_number("Height (cm): ", float)

    print("\nGender:")
    gender = _prompt_choice("Select: ", {"1": ("male", "Male"), "2": ("female", "Female")})

    print("\nActivity Level:")
    activity = _prompt_choice("Select (1–5): ", ACTIVITY_OPTIONS)

    print("\nFitness Goal:")
    goal = _prompt_choice("Select (1–3): ", GOAL_OPTIONS)

    print("\nExperience Level:")
    experience = _prompt_choice("Select (1–3): ", EXPERIENCE_OPTIONS)

    user_data = {
        "name":             name,
        "age":              age,
        "weight_kg":        weight,
        "height_cm":        height,
        "gender":           gender,
        "activity_level":   activity,
        "goal":             goal,
        "experience_level": experience,
    }

    print("\nGenerating your plan...\n")

    agent = FitnessAgent()
    result = agent.run(user_data)

    if not result["success"]:
        print("Input validation failed:")
        for err in result["errors"]:
            print(f"  - {err}")
        sys.exit(1)

    _print_plan(result)


if __name__ == "__main__":
    main()
